---
- name: Backup cisco configurations
  hosts: appc_cisco_mgmt_sw 
  gather_facts: false
  connection: network_cli

  vars:
    ansible_network_os: ios

  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars
      delegate_to: localhost

  tasks:
    - name: Collect device running configs and write to a temporary file
      ansible.builtin.import_role:
        name: role-cisco-config-backup
      vars:
        _backup_: true
        _tmp_root_dir_: "{{ tmp_base_dir }}"
        _local_file_path_: "{{ tmp_base_dir }}/{{ git_repo_config_backup_dir_path }}/{{ config_backup_file_name }}"