---
- name: Collect cisco device running configs
  cisco.ios.ios_command:
    commands: show running-config
  register: config_output
  ignore_errors: yes

# regex_replace('\r\n', '\n'): Ensures that the configuration is formatted properly with new lines,
# in case the original output contains carriage return and line feed (\r\n).
- name: Ensure the config is properly formatted
  ansible.builtin.set_fact:
    formatted_config: "{{ config_output.stdout[0] | regex_replace('\r\n', '\n') }}"
  delegate_to: localhost
  ignore_errors: true
  when: config_output["failed"] == false

- name: Save the configuration to the temporary file
  ansible.builtin.copy:
    content: "{{ formatted_config }}"
    dest: "{{ _local_file_path_ }}"
  delegate_to: localhost
  ignore_errors: true
  when: config_output["failed"] == false
